name: dbt CI/CD
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - name: Install dbt and dependencies
        run: |
          pip install dbt-postgres  # or dbt-snowflake, dbt-bigquery, etc.
          pip install -r requirements.txt  # if you have one
          dbt deps

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_northwind:
            target: prod
            outputs:
              prod:
                type: postgres
                host: ${{ secrets.SUPABASE_HOST }}
                user: ${{ secrets.SUPABASE_USER }}
                password: ${{ secrets.SUPABASE_PASSWORD }}
                port: ${{ secrets.SUPABASE_PORT }}
                dbname: ${{ secrets.SUPABASE_DBNAME }}
                schema: public
                threads: 4
          EOF

      - name: Run dbt
        run: |
          dbt debug
          dbt run --target prod
          dbt test --target prod